#!/usr/bin/env python3
from __future__ import annotations

"""
valuation_probe.py

Purpose
-------
This script is an end-to-end valuation test harness for the sports card pricing pipeline.
It is used to validate that the full workflow is functioning correctly from normalized comps
through final blended valuation.

It does NOT scrape new data itself.
Instead, it reads an existing normalized comps CSV that was previously generated by the
sold-comps scraper pipeline, then runs the downstream pricing logic against it.
"""

import base64
import csv
import html as html_lib
import json
import subprocess
import sys
import urllib.request
import webbrowser
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

# Add project root so imports like `from utils...` work when run as a script
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from providers.ebay_comp_buckets import bucket_summary, build_comp_buckets
from providers.ebay_comp_filter import CompFilterCriteria, filter_comps
from providers.liquidity_model_selector import (
    LiquiditySelectorInput,
    MODEL_A_NAME,
    MODEL_B_NAME,
    select_liquidity_model,
)
from providers.valuation_engine import MODEL_A, MODEL_B, apply_liquidity_model
from utils.prompt_utils import autocomplete_object, select_choice, text_input
from utils.pretty_table import print_aligned_table

SPORTS = ["Baseball", "Football", "Basketball", "Hockey"]
COMPS_ROOT = PROJECT_ROOT / "data" / "csv_dumps" / "comps"

FILTERED_ROW_COLUMNS = [
    "price_value",
    "shipping_value",
    "total_value",
    "sold_date_value",
    "listing_type",
    "is_best_offer",
    "card_number_guess",
    "grader_norm",
    "grade_value",
    "title_short",
    "valuation_lane",
    "valuation_range",
    "valuation_note",
    "item_id",
    "search_results_url",
    "search_result_item_url",
    "result_position_on_page",
    "search_page_number",
    "search_keywords",
    "search_sort_order",
]

MAJOR_GRADERS = {"PSA", "BGS", "SGC", "CGC", "CSG"}


@dataclass(frozen=True)
class ScarcityAdjustmentSummary:
    grader: str
    grade_value: Optional[float]
    top_grade_pop: Optional[int]
    top_grade_label: str
    eligible: bool
    applied: bool
    market_supported: bool
    scarcity_tier: str
    premium_pct: float
    adjusted_high_value: Optional[float]
    seller_max_value: Optional[float]
    reason: str


@dataclass(frozen=True)
class LaneResult:
    lane_label: str
    grader: str
    grade_value: Optional[float]
    rows: list[dict[str, Any]]
    valuation_range: str
    valuation_note: str
    recent_median_value: Optional[float]
    blended_value: Optional[float]
    seller_max_value: Optional[float]
    selected_model_name: str
    scarcity_summary: ScarcityAdjustmentSummary
    outlier_high_rows: list[str]
    outlier_low_rows: list[str]



def _norm(value: str | None) -> str:
    return " ".join((value or "").strip().split())


def _safe_lower(value: str | None) -> str:
    return _norm(value).lower()


def _shorten(text: str | None, max_len: int = 60) -> str:
    value = _norm(text)
    if len(value) <= max_len:
        return value
    return value[: max_len - 3] + "..."


def _parse_optional_float(value: str | None) -> Optional[float]:
    text = _norm(value)
    if not text:
        return None
    try:
        return float(text)
    except ValueError as exc:
        raise ValueError(f"Could not parse float from: {value!r}") from exc


def _parse_boolish(value: Any) -> Any:
    if isinstance(value, bool):
        return value
    if value is None:
        return None
    text = _safe_lower(str(value))
    if text in {"true", "t", "yes", "y", "1"}:
        return True
    if text in {"false", "f", "no", "n", "0"}:
        return False
    return value


def _parse_optional_number(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return value
    text = _norm(str(value))
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return value


def normalize_grader(value: str | None) -> str:
    return _safe_lower(value).upper()


def coerce_inherited_grade_value(value: Any) -> Optional[float]:
    if value in (None, ""):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return _parse_optional_float(str(value))


def prompt_sport_scrollable() -> str:
    return select_choice(
        "Choose Sport:",
        SPORTS,
        default="Baseball",
    )


def prompt_year_filter_optional() -> str:
    return text_input("Enter Year filter (optional — press Enter for all years):") or ""


def prompt_player_name_optional() -> str:
    return text_input("Enter Player Name filter (optional — press Enter for none):") or ""


def prompt_card_number_optional() -> str:
    return text_input("Enter Card # filter (optional — press Enter to skip):") or ""


def prompt_grade_company_optional() -> str:
    return text_input("Enter Grade Company filter (optional — PSA/SGC/BGS/etc):") or ""


def prompt_grade_value_optional() -> Optional[float]:
    raw = text_input("Enter Grade Value filter (optional — 10/9/8.5/etc):")
    return _parse_optional_float(raw)


def prompt_top_grade_population_optional(top_grade_label: str) -> Optional[int]:
    raw = text_input(
        f"Enter {top_grade_label} population (optional — press Enter to skip scarcity adjustment):"
    )
    text = _norm(raw)
    if not text:
        return None
    try:
        value = int(text)
    except ValueError as exc:
        raise ValueError(
            f"Could not parse integer from {top_grade_label} population input: {raw!r}"
        ) from exc
    if value < 0:
        raise ValueError(f"{top_grade_label} population cannot be negative.")
    return value


def prompt_require_graded_optional() -> Optional[bool]:
    choice = select_choice(
        "Graded filter:",
        ["Any", "Graded only", "Raw only"],
        default="Any",
    )
    if choice == "Graded only":
        return True
    if choice == "Raw only":
        return False
    return None


def prompt_manual_model_override_optional() -> str:
    choice = select_choice(
        "Liquidity model override:",
        ["Auto", "Model A", "Model B"],
        default="Auto",
    )
    if choice == "Auto":
        return ""
    return choice


def get_comps_output_dir(sport: str) -> Path:
    return COMPS_ROOT / sport.strip().lower()


def list_normalized_comp_files(sport: str) -> list[Path]:
    sport_dir = get_comps_output_dir(sport)
    if not sport_dir.exists():
        return []

    files = [p for p in sport_dir.glob("*_normalized.csv") if p.is_file()]
    return sorted(files, key=lambda p: p.name.lower())


def filter_comp_files_by_year(files: list[Path], year_filter: str) -> list[Path]:
    year_text = _norm(year_filter)
    if not year_text:
        return files

    return [p for p in files if year_text in p.name]


def prompt_normalized_csv_file(files: list[Path]) -> Path:
    if not files:
        raise FileNotFoundError("No normalized CSV files were found for the selected scope.")

    selected = autocomplete_object(
        "Choose Normalized CSV (type to filter, Enter to select):",
        files,
        label_getter=lambda p: p.name,
        value_getter=lambda p: str(p),
    )
    return selected


def load_csv_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Normalized comps CSV not found: {path}")

    rows: list[dict[str, Any]] = []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for raw in reader:
            row = dict(raw)

            for key in ["price_value", "shipping_value", "total_value", "grade_value"]:
                row[key] = _parse_optional_number(row.get(key))

            row["is_best_offer"] = _parse_boolish(row.get("is_best_offer"))
            row["is_graded"] = _parse_boolish(row.get("is_graded"))

            rows.append(row)

    return rows


def infer_search_context_from_filename(path: Path) -> dict[str, str]:
    stem = path.stem
    if stem.endswith("_normalized"):
        stem = stem[:-11]

    parts = stem.split("_")
    context = {
        "sport": parts[0] if len(parts) > 0 else "",
        "year": parts[1] if len(parts) > 1 else "",
        "set_guess": " ".join(parts[2:]) if len(parts) > 2 else "",
    }
    return context


def _get_top_grade_label(grader: str, grade_value: Optional[float]) -> Optional[str]:
    g = normalize_grader(grader)

    if g == "PSA" and grade_value == 10.0:
        return "PSA 10"
    if g == "SGC" and grade_value == 10.0:
        return "SGC 10"
    if g == "CGC" and grade_value == 10.0:
        return "CGC 10"
    if g == "CSG" and grade_value == 10.0:
        return "CSG 10"
    if g == "BGS" and grade_value == 10.0:
        return "BGS 10"
    if g == "BGS" and grade_value == 9.5:
        return "BGS 9.5"

    return None


def _is_top_grade_filter(grader: str, grade_value: Optional[float]) -> bool:
    return _get_top_grade_label(grader, grade_value) is not None


def _count_top_grade_filtered_rows(
    rows: list[dict[str, Any]],
    grader: str,
    grade_value: Optional[float],
) -> int:
    target_grader = normalize_grader(grader)
    count = 0
    for row in rows:
        if (
            normalize_grader(row.get("grader_norm")) == target_grader
            and row.get("grade_value") == grade_value
        ):
            count += 1
    return count


def build_scarcity_adjustment(
    *,
    grader: str,
    grade_value: Optional[float],
    top_grade_pop: Optional[int],
    selection_model_name: str,
    filtered_rows: list[dict[str, Any]],
    strong_bin_count: int,
    blended_value: Optional[float],
) -> ScarcityAdjustmentSummary:
    normalized_grader = normalize_grader(grader)
    top_grade_label = _get_top_grade_label(normalized_grader, grade_value) or "(not applicable)"

    if not _is_top_grade_filter(normalized_grader, grade_value):
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=top_grade_pop,
            top_grade_label=top_grade_label,
            eligible=False,
            applied=False,
            market_supported=False,
            scarcity_tier="not applicable",
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason="Scarcity influence is only evaluated for top-grade valuations from major graders "
            "(PSA 10, SGC 10, BGS 9.5/10, CGC 10, CSG 10).",
        )

    if top_grade_pop is None:
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=None,
            top_grade_label=top_grade_label,
            eligible=True,
            applied=False,
            market_supported=False,
            scarcity_tier="none",
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason=f"No {top_grade_label} population was provided, so no scarcity adjustment was applied.",
        )

    if selection_model_name != MODEL_B_NAME:
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=top_grade_pop,
            top_grade_label=top_grade_label,
            eligible=True,
            applied=False,
            market_supported=False,
            scarcity_tier="none",
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason="Scarcity adjustment requires a high-liquidity Model B selection.",
        )

    top_grade_comp_count = _count_top_grade_filtered_rows(filtered_rows, normalized_grader, grade_value)
    market_supported = top_grade_comp_count >= 2 or (top_grade_comp_count >= 1 and strong_bin_count > 0)
    if not market_supported:
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=top_grade_pop,
            top_grade_label=top_grade_label,
            eligible=True,
            applied=False,
            market_supported=False,
            scarcity_tier="none",
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason=(
                f"{top_grade_label} scarcity needs market support "
                "(at least 2 matching graded comps, or 1 comp plus strong BIN support)."
            ),
        )

    if top_grade_pop <= 10:
        scarcity_tier = "strong"
        premium_pct = 0.15
    elif top_grade_pop <= 25:
        scarcity_tier = "moderate"
        premium_pct = 0.10
    elif top_grade_pop <= 50:
        scarcity_tier = "light"
        premium_pct = 0.05
    else:
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=top_grade_pop,
            top_grade_label=top_grade_label,
            eligible=True,
            applied=False,
            market_supported=True,
            scarcity_tier="none",
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason=f"{top_grade_label} population {top_grade_pop} does not qualify for a scarcity premium.",
        )

    if blended_value is None:
        return ScarcityAdjustmentSummary(
            grader=normalized_grader,
            grade_value=grade_value,
            top_grade_pop=top_grade_pop,
            top_grade_label=top_grade_label,
            eligible=True,
            applied=False,
            market_supported=True,
            scarcity_tier=scarcity_tier,
            premium_pct=0.0,
            adjusted_high_value=None,
            seller_max_value=None,
            reason="Base blended valuation was unavailable, so no scarcity premium was applied.",
        )

    adjusted_high_value = round(blended_value * (1.0 + premium_pct), 2)
    seller_max_value = round(adjusted_high_value * 1.05, 2)

    return ScarcityAdjustmentSummary(
        grader=normalized_grader,
        grade_value=grade_value,
        top_grade_pop=top_grade_pop,
        top_grade_label=top_grade_label,
        eligible=True,
        applied=True,
        market_supported=True,
        scarcity_tier=scarcity_tier,
        premium_pct=premium_pct,
        adjusted_high_value=adjusted_high_value,
        seller_max_value=seller_max_value,
        reason=(
            f"{top_grade_label} population {top_grade_pop} with Model B liquidity and supporting comps "
            f"yields a {scarcity_tier} scarcity signal."
        ),
    )



def _round_display_value(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(float(value) + 0.5)
    except (TypeError, ValueError):
        return None


def _fmt_money(value: Any) -> str:
    rounded = _round_display_value(value)
    if rounded is None:
        return "(none)"
    return f"${rounded:,}"


def _format_range(low: Any, mid: Any, high: Any) -> str:
    low_s = _fmt_money(low)
    mid_s = _fmt_money(mid)
    high_s = _fmt_money(high)
    return f"{low_s}-{mid_s}-{high_s}"


def _parse_range_values(range_text: str | None) -> tuple[Optional[float], Optional[float], Optional[float]]:
    text = _norm(range_text)
    if not text:
        return (None, None, None)
    parts = [p.strip().replace("$", "").replace(",", "") for p in text.split("-")]
    if len(parts) != 3:
        return (None, None, None)
    values: list[Optional[float]] = []
    for part in parts:
        try:
            values.append(float(part))
        except ValueError:
            values.append(None)
    return (values[0], values[1], values[2])


def _grade_label(value: Optional[float]) -> str:
    if value is None:
        return ""
    if float(value).is_integer():
        return str(int(value))
    return str(value)


def _infer_lane_label(grader: str, grade_value: Optional[float], require_graded: Optional[bool]) -> str:
    normalized = normalize_grader(grader)
    if require_graded is False:
        return "eBay Raw"
    if normalized and grade_value is not None:
        return f"eBay {normalized} {_grade_label(grade_value)}"
    if normalized:
        return f"eBay {normalized}"
    if require_graded is True:
        return "eBay Graded"
    return "eBay Raw"


def _infer_grader_note(grader: str, grade_value: Optional[float], require_graded: Optional[bool]) -> Optional[str]:
    normalized = normalize_grader(grader)
    if normalized and grade_value is not None:
        return f"{normalized} {_grade_label(grade_value)}"
    if normalized:
        return normalized
    if require_graded is True:
        return "graded only"
    if require_graded is False:
        return "raw only"
    return None


def _build_valuation_note(
    *,
    lane_label: str,
    model_label: str,
    comp_count: int,
    grader_note: Optional[str],
    scarcity_pct: float,
) -> str:
    parts = [lane_label]
    if grader_note and grader_note.lower() not in lane_label.lower():
        parts.append(grader_note)
    parts.append(f"{comp_count} comp" if comp_count == 1 else f"{comp_count} comps")
    if scarcity_pct > 0:
        parts.append(f"scarcity +{scarcity_pct:.0%}")
    return " | ".join(parts)


def _safe_slug(text: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in text)
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-") or "lane"


def _parse_sold_date(value: Any) -> str:
    return _norm(str(value or ""))


def _preferred_listing_url(row: dict[str, Any]) -> str:
    return (
        _norm(str(row.get("search_result_item_url") or ""))
        or _norm(str(row.get("item_url") or ""))
        or _norm(str(row.get("listing_url") or ""))
        or _norm(str(row.get("url") or ""))
        or _norm(str(row.get("item_link") or ""))
    )


def _search_results_fallback_url(row: dict[str, Any]) -> str:
    return _norm(str(row.get("search_results_url") or ""))


def _search_page_link_label(row: dict[str, Any]) -> str:
    position = _norm(str(row.get("result_position_on_page") or ""))
    if position:
        return f"Search page: item #{position}"
    return "Search page"


def _find_outlier_row_ids(rows: list[dict[str, Any]], recent_median_value: Optional[float]) -> tuple[list[str], list[str]]:
    if not rows:
        return ([], [])

    priced_rows: list[tuple[float, str]] = []
    for idx, row in enumerate(rows):
        price = row.get("price_value")
        if price is None:
            continue
        try:
            price_value = float(price)
        except (TypeError, ValueError):
            continue
        row_id = str(row.get("_row_id") or f"row-{idx}")
        priced_rows.append((price_value, row_id))

    if not priced_rows:
        return ([], [])

    high_value = max(price for price, _ in priced_rows)
    low_value = min(price for price, _ in priced_rows)

    high_ids = [row_id for price, row_id in priced_rows if price == high_value]
    low_ids = [row_id for price, row_id in priced_rows if price == low_value]
    return (high_ids, low_ids)


def _build_filtered_row_display(rows: list[dict[str, Any]], lane_label: str, valuation_range: str, valuation_note: str) -> list[dict[str, Any]]:
    display_rows: list[dict[str, Any]] = []
    for row in rows:
        display_rows.append(
            {
                "price_value": row.get("price_value") if row.get("price_value") is not None else "",
                "shipping_value": row.get("shipping_value") if row.get("shipping_value") is not None else "",
                "total_value": row.get("total_value") if row.get("total_value") is not None else "",
                "sold_date_value": row.get("sold_date_value") or "",
                "listing_type": row.get("listing_type") or "",
                "is_best_offer": row.get("is_best_offer"),
                "card_number_guess": row.get("card_number_guess") or "",
                "grader_norm": row.get("grader_norm") or "",
                "grade_value": row.get("grade_value") if row.get("grade_value") is not None else "",
                "title_short": _shorten(row.get("title"), 60),
                "valuation_lane": lane_label,
                "valuation_range": valuation_range,
                "valuation_note": valuation_note,
                "item_id": row.get("item_id") or "",
                "search_results_url": row.get("search_results_url") or "",
                "search_result_item_url": row.get("search_result_item_url") or "",
                "result_position_on_page": row.get("result_position_on_page") or "",
                "search_page_number": row.get("search_page_number") or "",
                "search_keywords": row.get("search_keywords") or "",
                "search_sort_order": row.get("search_sort_order") or "",
            }
        )
    return display_rows


def _group_rows_for_valuation(
    rows: list[dict[str, Any]],
    *,
    grader: str,
    grade_value: Optional[float],
    require_graded: Optional[bool],
) -> list[dict[str, Any]]:
    normalized_grader = normalize_grader(grader)
    # Explicit lane: keep as single lane.
    if normalized_grader or grade_value is not None or require_graded is False:
        return [
            {
                "lane_label": _infer_lane_label(normalized_grader, grade_value, require_graded),
                "rows": rows,
                "lane_grader": normalized_grader,
                "lane_grade_value": grade_value,
                "lane_require_graded": require_graded,
            }
        ]

    # Generic broad search with graded only: split by exact grader+grade.
    if require_graded is True:
        grouped: dict[tuple[str, Optional[float]], list[dict[str, Any]]] = {}
        for row in rows:
            g = normalize_grader(row.get("grader_norm"))
            gv = row.get("grade_value")
            key = (g or "GRADED", gv)
            grouped.setdefault(key, []).append(row)
        groups = []
        for (g, gv), lane_rows in sorted(grouped.items(), key=lambda item: (item[0][0], item[0][1] if item[0][1] is not None else -1), reverse=False):
            groups.append(
                {
                    "lane_label": _infer_lane_label(g, gv, True),
                    "rows": lane_rows,
                    "lane_grader": g,
                    "lane_grade_value": gv,
                    "lane_require_graded": True,
                }
            )
        return groups

    # Mixed generic search: raw + exact graded lanes.
    raw_rows = [r for r in rows if not normalize_grader(r.get("grader_norm"))]
    graded_rows = [r for r in rows if normalize_grader(r.get("grader_norm"))]
    groups: list[dict[str, Any]] = []
    if raw_rows:
        groups.append(
            {
                "lane_label": "eBay Raw",
                "rows": raw_rows,
                "lane_grader": "",
                "lane_grade_value": None,
                "lane_require_graded": False,
            }
        )
    graded_grouped: dict[tuple[str, Optional[float]], list[dict[str, Any]]] = {}
    for row in graded_rows:
        g = normalize_grader(row.get("grader_norm"))
        gv = row.get("grade_value")
        graded_grouped.setdefault((g, gv), []).append(row)
    for (g, gv), lane_rows in sorted(graded_grouped.items(), key=lambda item: (item[0][0], item[0][1] if item[0][1] is not None else -1), reverse=False):
        groups.append(
            {
                "lane_label": _infer_lane_label(g, gv, True),
                "rows": lane_rows,
                "lane_grader": g,
                "lane_grade_value": gv,
                "lane_require_graded": True,
            }
        )
    return groups or [
        {
            "lane_label": "eBay Raw",
            "rows": rows,
            "lane_grader": "",
            "lane_grade_value": None,
            "lane_require_graded": require_graded,
        }
    ]


def _best_card_image_data_uri(rows: list[dict[str, Any]]) -> Optional[str]:
    image_fields = [
        "image_url",
        "img_url",
        "picture_url",
        "gallery_url",
        "galleryURL",
        "pictureURL",
        "thumbnail_url",
        "image",
        "img",
    ]

    # Prefer direct image fields from the normalized/scraped rows.
    for row in rows[:20]:
        image_url = ""
        for field in image_fields:
            image_url = _norm(str(row.get(field) or ""))
            if image_url:
                break
        if not image_url:
            continue

        try:
            req = urllib.request.Request(
                image_url,
                headers={"User-Agent": "Mozilla/5.0", "Referer": "https://www.ebay.com/"},
            )
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = resp.read()
                content_type = resp.headers.get_content_type() or "image/jpeg"
            if data:
                encoded = base64.b64encode(data).decode("ascii")
                return f"data:{content_type};base64,{encoded}"
        except Exception:
            # Fallback: if embedding fails, still use the direct image URL.
            return image_url

    return None


def _open_html_report(report_path: Path) -> None:
    report_path = report_path.resolve()
    try:
        subprocess.run(["open", str(report_path)], check=False)
        return
    except Exception:
        pass
    try:
        webbrowser.open(report_path.as_uri(), new=2)
    except Exception:
        pass


def _company_order(company: str) -> int:
    order = {"PSA": 0, "BGS": 1, "SGC": 2, "CGC": 3, "TAG": 4, "CSG": 5}
    return order.get(company, 99)


def _lane_section_sort_key(lane: LaneResult) -> tuple[int, int, float]:
    grader = normalize_grader(lane.grader)
    if not grader:
        return (99, 99, 99.0)

    gv = lane.grade_value
    try:
        gv_num = float(gv) if gv is not None else None
    except (TypeError, ValueError):
        gv_num = None

    if gv_num == 10.0:
        bucket_order = 0
    elif gv_num == 9.0:
        bucket_order = 1
    else:
        bucket_order = 2

    return (_company_order(grader), bucket_order, -(gv_num if gv_num is not None else -1.0))


def _display_bucket_for_lane(lane: LaneResult) -> str:
    if lane.lane_label == "eBay Raw":
        return "Raw"
    g = normalize_grader(lane.grader)
    if not g:
        return "Other"
    gv = lane.grade_value
    if gv == 10 or gv == 10.0:
        return "10"
    if gv == 9 or gv == 9.0:
        return "9"
    return "8 and below"


def _build_dashboard_groups(lane_results: list[LaneResult]) -> list[dict[str, Any]]:
    groups: list[dict[str, Any]] = []
    raw_lane = next((l for l in lane_results if l.lane_label == "eBay Raw"), None)
    if raw_lane:
        groups.append({"kind": "raw", "title": "Raw", "tiles": [raw_lane]})

    companies = sorted({normalize_grader(l.grader) for l in lane_results if normalize_grader(l.grader)}, key=_company_order)
    for company in companies:
        wanted = ["10", "9", "8 and below"]
        tiles = []
        for bucket in wanted:
            lane = next((l for l in lane_results if normalize_grader(l.grader) == company and _display_bucket_for_lane(l) == bucket), None)
            if lane:
                tiles.append({"bucket": bucket, "lane": lane})
            else:
                tiles.append({"bucket": bucket, "lane": None})
        groups.append({"kind": "company", "title": company, "tiles": tiles})
    return groups


def _arrow_html(lane: LaneResult) -> str:
    parts: list[str] = []
    if lane.outlier_high_rows:
        target = lane.outlier_high_rows[0]
        parts.append(f'<a class="outlier-arrow up" href="#{html_lib.escape(target)}" title="Jump to high outlier">▲</a>')
    if lane.outlier_low_rows:
        target = lane.outlier_low_rows[0]
        parts.append(f'<a class="outlier-arrow down" href="#{html_lib.escape(target)}" title="Jump to low outlier">▼</a>')
    if not parts:
        return ""
    return f'<span class="outlier-arrows">{"".join(parts)}</span>'


def _tile_class(company: str) -> str:
    if company == "Raw":
        return "tile raw"
    if company == "PSA":
        return "tile psa"
    if company == "BGS":
        return "tile bgs"
    return "tile"


def _tooltip_icon(title: str) -> str:
    return f'<span class="tooltip-icon" title="{html_lib.escape(title)}" aria-label="More info">!</span>'


def _metric_grid_html(lane: Optional[LaneResult]) -> str:
    labels = [
        ("Recent", "Median", "Recent Median = recent comp anchor based on the lane's recent median sold price."),
        ("Liquidity", "Blend", "Liquidity Blend = modeled valuation using the selected liquidity weighting for this lane."),
        ("Scarcity", "High", "Scarcity High = modeled high-side value after scarcity logic when applicable. This is not the highest observed comp sale."),
    ]

    if lane is None:
        values = ["—", "—", "—"]
    else:
        low_value, mid_value, high_value = _parse_range_values(lane.valuation_range)
        values = [
            html_lib.escape(_fmt_money(low_value)),
            html_lib.escape(_fmt_money(mid_value)),
            html_lib.escape(_fmt_money(high_value)),
        ]

    cells: list[str] = []
    for value_html, (line1, line2, tooltip) in zip(values, labels):
        cells.append(
            f"""
            <div class="metric-cell">
              <div class="metric-value-row">
                <div class="metric-value">{value_html}</div>
              </div>
              <div class="metric-label-wrap">
                <div class="metric-label-line">{html_lib.escape(line1)}</div>
                <div class="metric-label-line">{html_lib.escape(line2)}</div>
              </div>
            </div>
            """
        )
    return f'<div class="metric-grid">{"".join(cells)}</div>'


def _outlier_summary_html(lane: Optional[LaneResult]) -> str:
    tooltip = (
        "High outlier is the highest observed sale in this lane. "
        "Low outlier is the lowest observed sale in this lane."
    )
    if lane is None:
        high_part = '<span class="outlier-label">High outlier:</span> <span class="outlier-value">—</span>'
        low_part = '<span class="outlier-label">Low outlier:</span> <span class="outlier-value">—</span>'
    else:
        high_target = lane.outlier_high_rows[0] if lane.outlier_high_rows else ""
        low_target = lane.outlier_low_rows[0] if lane.outlier_low_rows else ""

        high_value = None
        if high_target:
            for row in lane.rows:
                if str(row.get("_row_id") or "") == high_target:
                    high_value = row.get("price_value")
                    break
        low_value = None
        if low_target:
            for row in lane.rows:
                if str(row.get("_row_id") or "") == low_target:
                    low_value = row.get("price_value")
                    break

        high_money = html_lib.escape(_fmt_money(high_value))
        low_money = html_lib.escape(_fmt_money(low_value))

        if high_target:
            high_value_html = f'<a class="outlier-link up" href="#{html_lib.escape(high_target)}">{high_money}</a>'
        else:
            high_value_html = f'<span class="outlier-value">{high_money}</span>'

        if low_target:
            low_value_html = f'<a class="outlier-link down" href="#{html_lib.escape(low_target)}">{low_money}</a>'
        else:
            low_value_html = f'<span class="outlier-value">{low_money}</span>'

        high_part = f'<span class="outlier-label">High outlier:</span> {high_value_html}'
        low_part = f'<span class="outlier-label">Low outlier:</span> {low_value_html}'

    return (
        f'<div class="outlier-summary">'
        f'<span class="outlier-part">{high_part}</span>'
        f'<span class="outlier-separator">|</span>'
        f'<span class="outlier-part">{low_part}</span>'
        f'</div>'
    )


def _build_html_report(*, card_title: str, subtitle: str, source_csv: Path, lane_results: list[LaneResult]) -> str:
    all_rows: list[dict[str, Any]] = []
    for lane in lane_results:
        all_rows.extend(lane.rows)
    image_data_uri = _best_card_image_data_uri(all_rows)

    dashboard_groups = _build_dashboard_groups(lane_results)

    raw_tile_html = ""
    tiles_html: list[str] = []
    for group in dashboard_groups:
        if group["kind"] == "raw":
            lane = group["tiles"][0]
            raw_tile_html = f"""
            <div class="hero-raw-inline">
                <div class="{_tile_class('Raw')} wide">
                    <div class="tile-header"><span class="tile-title">Raw</span>{_arrow_html(lane)}</div>
                    {_metric_grid_html(lane)}
                    {_outlier_summary_html(lane)}
                    <div class="tile-note">{html_lib.escape(lane.valuation_note)}</div>
                </div>
            </div>
            """
            continue

        company = group["title"]
        row_tiles = []
        for entry in group["tiles"]:
            bucket = entry["bucket"]
            lane = entry["lane"]
            if lane is None:
                note_html = "No comps"
                arrows = ""
            else:
                note_html = html_lib.escape(lane.valuation_note)
                arrows = _arrow_html(lane)
            row_tiles.append(f"""
            <div class="{_tile_class(company)}">
              <div class="tile-header"><span class="tile-title">{html_lib.escape(company)} {html_lib.escape(bucket)}</span>{arrows}</div>
              {_metric_grid_html(lane)}
              {_outlier_summary_html(lane)}
              <div class="tile-note">{note_html}</div>
            </div>
            """)
        tiles_html.append(f"""
        <div class="company-row">
          <div class="company-tiles">
            {''.join(row_tiles)}
          </div>
        </div>
        """)

    row_blocks: list[str] = []
    sorted_lane_results = sorted(lane_results, key=_lane_section_sort_key)
    for lane in sorted_lane_results:
        row_blocks.append(f'<h3 class="lane-heading">{html_lib.escape(lane.lane_label)}</h3>')
        row_blocks.append('<div class="listing-table">')
        for idx, row in enumerate(lane.rows):
            row_id = row.get("_row_id") or f"{_safe_slug(lane.lane_label)}-{idx}"
            extra_class = ""
            badge = ""
            if row_id in lane.outlier_high_rows:
                extra_class = " listing-row outlier-high"
                badge = '<span class="row-badge up">▲ high outlier</span>'
            elif row_id in lane.outlier_low_rows:
                extra_class = " listing-row outlier-low"
                badge = '<span class="row-badge down">▼ low outlier</span>'
            else:
                extra_class = " listing-row"

            row_link = _preferred_listing_url(row)
            search_page_link = _search_results_fallback_url(row)

            link_parts: list[str] = []
            if row_link:
                link_parts.append(
                    f'<a class="listing-link" href="{html_lib.escape(row_link)}" target="_blank" rel="noopener noreferrer">View listing</a>'
                )
            if search_page_link:
                search_page_label = _search_page_link_label(row)
                link_parts.append(
                    f'<a class="listing-link" href="{html_lib.escape(search_page_link)}" target="_blank" rel="noopener noreferrer">{html_lib.escape(search_page_label)}</a>'
                )
            link_html = " ".join(link_parts)

            row_blocks.append(f"""
            <div id="{html_lib.escape(str(row_id))}" class="{extra_class}">
              <div class="listing-title">{html_lib.escape(_norm(str(row.get('title') or '')))} {badge}</div>
              <div class="listing-meta">
                <span>{html_lib.escape(lane.lane_label)}</span>
                <span>{html_lib.escape(normalize_grader(row.get('grader_norm')) or '(raw)')}</span>
                <span>{html_lib.escape(_grade_label(row.get('grade_value')) or '')}</span>
                <span>{html_lib.escape(_fmt_money(row.get('price_value')))}</span>
                <span>{html_lib.escape(_parse_sold_date(row.get('sold_date_value')))}</span>
                {link_html}
              </div>
            </div>
            """)
        row_blocks.append('</div>')

    image_html = f'<img class="card-image" src="{image_data_uri}" alt="Card image" />' if image_data_uri else '<div class="card-fallback">No card image</div>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{html_lib.escape(card_title)} valuation report</title>
<style>
body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  margin: 0;
  background: #0f172a;
  color: #e5e7eb;
}}
.page {{
  max-width: 1280px;
  margin: 0 auto;
  padding: 24px;
}}
.subtitle-model {{
  color: #ffffff;
}}
.report-legend {{
  margin-top: 16px;
  display: grid;
  gap: 8px;
}}
.legend-row {{
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #94a3b8;
  font-size: 13px;
}}
.listing-link {{
  color: #93c5fd;
  text-decoration: none;
  font-weight: 600;
}}
.listing-link:hover {{
  text-decoration: underline;
}}
.hero {{
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
  gap: 12px;
  margin-bottom: 24px;
  align-items: stretch;
}}
.hero-right {{
  min-width: 0;
}}
.hero-raw-inline {{
  margin-top: 16px;
}}
.hero-raw-row .metric-cell {{
  display: flex;
  align-items: center;
  gap: 6px;
}}
.hero-raw-row .metric-value-row {{
  display: contents;
}}
.hero-raw-row .metric-value {{
  order: 1;
  margin-bottom: 0;
}}
.hero-raw-row {{
  margin-bottom: 0;
}}
.hero-raw-row .metric-label-wrap {{
  order: 2;
  display: inline-flex;
  align-items: center;
  gap: 0;
}}
.hero-raw-row .metric-label-line {{
  display: inline;
  white-space: nowrap;
}}
.hero-raw-row .metric-label-line + .metric-label-line::before {{
  content: " ";
}}
.hero-raw-row .metric-value-row .tooltip-icon {{
  order: 3;
  margin-left: 6px;
}}
.card-panel {{
  padding: 8px;
  overflow: hidden;
  min-width: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
}}
.card-image {{
  width: 100%;
  height: 100%;
  display: block;
  object-fit: contain;
  object-position: center center;
  box-sizing: border-box;
}}
.card-fallback {{
  width: 100%;
  height: 100%;
  min-height: 320px;
  display: grid;
  place-items: center;
  background: linear-gradient(135deg, #1f2937, #0b1220);
  color: #9ca3af;
  font-weight: 600;
}}
.card-panel, .summary-panel, .company-row, .raw-row, .listing-table {{
  background: #111827;
  border: 1px solid #243041;
  border-radius: 16px;
  box-shadow: 0 12px 30px rgba(0,0,0,.25);
}}
.summary-panel {{
  padding: 20px;
  min-width: 0;
  align-self: start;
}}
.summary-panel h1 {{
  font-size: 24px;
}}
.subtitle {{
  color: #94a3b8;
  margin-top: 4px;
}}
.raw-row {{
  padding: 14px;
  margin-bottom: 16px;
}}
.company-row {{
  padding: 14px;
  margin-bottom: 16px;
}}
.company-label {{
  font-size: 18px;
  font-weight: 700;
  margin-bottom: 10px;
}}
.company-tiles {{
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
}}
.tile {{
  border: 2px solid #334155;
  border-radius: 14px;
  padding: 14px;
  background: #0b1220;
}}
.tile.wide {{
  width: 100%;
}}
.tile.raw {{
  border-color: #f59e0b;
}}
.tile.psa {{
  border-color: #ef4444;
}}
.tile.bgs {{
  border-color: #3b82f6;
}}
.tile-header {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 8px;
}}
.tile-title {{
  font-weight: 700;
}}
.metric-grid {{
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 8px;
  margin-bottom: 10px;
}}
.metric-cell {{
  min-width: 0;
}}
.metric-value {{
  font-size: 24px;
  font-weight: 800;
  line-height: 1.1;
  margin-bottom: 0;
}}
.metric-value-row {{
  display: inline-flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 6px;
}}
.metric-label-wrap {{
  display: inline-grid;
  grid-template-columns: auto auto;
  column-gap: 6px;
  align-items: center;
  color: #94a3b8;
  font-size: 12px;
  line-height: 1.15;
}}
.metric-label-line {{
  white-space: nowrap;
}}
.tooltip-icon {{
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  min-width: 16px;
  height: 16px;
  min-height: 16px;
  border: 1.5px solid #d97706;
  border-radius: 999px;
  color: #d97706;
  background: rgba(217, 119, 6, 0.08);
  font-size: 11px;
  font-weight: 700;
  line-height: 1;
  cursor: help;
  user-select: none;
  box-sizing: border-box;
  flex-shrink: 0;
}}
.outlier-summary {{
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 6px;
  margin-bottom: 8px;
  color: #94a3b8;
  font-size: 12px;
}}
.outlier-part {{
  display: inline-flex;
  align-items: center;
  gap: 4px;
}}
.outlier-separator {{
  color: #64748b;
}}
.outlier-label {{
  color: #94a3b8;
}}
.outlier-value {{
  color: #e5e7eb;
  font-weight: 700;
}}
.outlier-link {{
  font-weight: 700;
  text-decoration: none;
}}
.outlier-link.up {{
  color: #22c55e;
}}
.outlier-link.down {{
  color: #ef4444;
}}
.outlier-link:hover {{
  text-decoration: underline;
}}
.tile-note {{
  color: #94a3b8;
  font-size: 13px;
}}
.outlier-arrows {{
  display: inline-flex;
  align-items: center;
  gap: 6px;
  margin-left: auto;
  flex-shrink: 0;
}}
.outlier-arrow {{
  display: inline-flex;
  align-items: center;
  justify-content: center;
  text-decoration: none;
  font-weight: 900;
  font-size: 18px;
  line-height: 1;
}}
.outlier-arrow.up {{
  color: #22c55e;
}}
.outlier-arrow.down {{
  color: #ef4444;
}}
.lane-heading {{
  margin: 22px 0 10px;
}}
.listing-table {{
  padding: 14px;
}}
.listing-row {{
  border: 1px solid #263345;
  border-radius: 10px;
  padding: 10px 12px;
  margin-bottom: 10px;
  background: #0b1220;
}}
.listing-row.outlier-high {{
  border-color: #22c55e;
  background: rgba(34, 197, 94, 0.10);
}}
.listing-row.outlier-low {{
  border-color: #ef4444;
  background: rgba(239, 68, 68, 0.10);
}}
.listing-title {{
  font-weight: 600;
  margin-bottom: 4px;
}}
.listing-meta {{
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  color: #94a3b8;
  font-size: 13px;
}}
.row-badge {{
  display: inline-block;
  margin-left: 8px;
  font-size: 12px;
  font-weight: 700;
}}
.row-badge.up {{
  color: #22c55e;
}}
.row-badge.down {{
  color: #ef4444;
}}
.footer-note {{
  margin-top: 18px;
  color: #94a3b8;
  font-size: 12px;
}}
</style>
</head>
<body>
<div class="page">
  <div class="hero">
   <div class="card-panel" id="card-panel">{image_html}</div>
    <div class="summary-panel" id="summary-panel">
      <h1>{html_lib.escape(card_title)}</h1>
      <div class="subtitle">{subtitle}</div>
      <div class="footer-note">Source CSV: {html_lib.escape(str(source_csv))}</div>

      <div class="report-legend">
        <div class="legend-row">{_tooltip_icon("Recent Median = recent comp anchor based on the lane's recent median sold price.")}<span>Recent Median</span></div>
        <div class="legend-row">{_tooltip_icon("Liquidity Blend = modeled valuation using the selected liquidity weighting for this lane.")}<span>Liquidity Blend</span></div>
        <div class="legend-row">{_tooltip_icon("Scarcity High = modeled high-side value after scarcity logic when applicable. This is not the highest observed comp sale.")}<span>Scarcity High</span></div>
        <div class="legend-row">{_tooltip_icon("High / Low Outlier = highest and lowest observed sold values in the lane.")}<span>High / Low Outlier</span></div>
      </div>

      {raw_tile_html}
    </div>
  </div>

  <section>
    {''.join(tiles_html)}
  </section>

  <section>
    {''.join(row_blocks)}
  </section>
</div>
</div>
<script>
(function () {{
  function syncCardPanelHeight() {{
    const cardPanel = document.getElementById("card-panel");
    const summaryPanel = document.getElementById("summary-panel");
    if (!cardPanel || !summaryPanel) return;

    cardPanel.style.height = `${{summaryPanel.clientHeight}}px`;
  }}

  window.addEventListener("load", syncCardPanelHeight);
  window.addEventListener("resize", syncCardPanelHeight);
}})();
</script>
</body>
</html>"""

def print_section(title: str) -> None:
    print(f"\n{title}")
    print("-" * len(title))


def print_selected_file_context(
    *,
    sport: str,
    year_filter: str,
    csv_path: Path,
) -> None:
    inferred = infer_search_context_from_filename(csv_path)

    print_section("Selected File")
    print(f"Sport folder:      {sport}")
    print(f"Year filter:       {year_filter or '(none)'}")
    print(f"Filename:          {csv_path.name}")
    print(f"Normalized CSV:    {csv_path}")
    print(f"Inferred year:     {inferred.get('year') or '(unknown)'}")
    print(f"Inferred context:  {inferred.get('set_guess') or '(unknown)'}")


def print_filter_context(
    *,
    player_name: str,
    card_number: str,
    grader: str,
    grade_value: Optional[float],
    require_graded: Optional[bool],
) -> None:
    print_section("Filter Context")
    print(f"Player:          {player_name or '(none)'}")
    print(f"Card #:          {card_number or '(none)'}")
    print(f"Grader filter:   {grader or '(none)'}")
    print(f"Grade filter:    {grade_value if grade_value is not None else '(none)'}")

    if require_graded is True:
        graded_label = "graded only"
    elif require_graded is False:
        graded_label = "raw only"
    else:
        graded_label = "any"

    print(f"Graded filter:   {graded_label}")


def build_filtered_row_display(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return _build_filtered_row_display(rows, "", "", "")


def print_filtered_rows_report(rows: list[dict[str, Any]], lane_label: str = "", valuation_range: str = "", valuation_note: str = "") -> None:
    title = "Filtered Rows Used For Valuation"
    if lane_label:
        title += f" — {lane_label}"
    print_section(title)
    print(f"Filtered row count: {len(rows)}")

    if not rows:
        print("(none)")
        return

    display_rows = _build_filtered_row_display(rows, lane_label, valuation_range, valuation_note)
    print_aligned_table(display_rows, FILTERED_ROW_COLUMNS)


def print_bucket_report(summary: dict[str, Any]) -> None:
    print_section("Bucket Summary")
    print(f"Recent median count:   {summary.get('recent_median_count')}")
    print(f"Recent median value:   {summary.get('recent_median_value')}")
    print(f"Strong BIN count:      {summary.get('strong_bin_count')}")
    print(f"Strong BIN value:      {summary.get('strong_bin_value')}")
    print(f"Peak auction count:    {summary.get('peak_auction_count')}")
    print(f"Peak auction value:    {summary.get('peak_auction_value')}")


def print_selector_report(selection) -> None:
    print_section("Liquidity Model Selection")
    print(f"Selected model:  {selection.selected_model_name}")
    print(f"Confidence:      {selection.confidence}")
    print(f"Reason:          {selection.reason}")
    print(f"Triggered by:    {', '.join(selection.triggered_by) if selection.triggered_by else '(none)'}")


def print_valuation_report(result) -> None:
    print_section("Valuation Result")
    print(f"Model:                     {result.model_name}")
    print(f"Weighting mode:            {result.weighting_mode}")
    print(f"Recent median value:       {result.recent_median_value}")
    print(f"Strong BIN value:          {result.strong_bin_value}")
    print(f"Peak auction value:        {result.peak_auction_value}")
    print(f"Effective recent weight:   {result.effective_recent_median_weight}")
    print(f"Effective strong BIN wt:   {result.effective_strong_bin_weight}")
    print(f"Effective auction weight:  {result.effective_peak_auction_weight}")
    print(f"Blended value:             {result.blended_value}")


def print_scarcity_report(summary: ScarcityAdjustmentSummary) -> None:
    print_section("Scarcity Signal")
    if not summary.eligible:
        print(f"Not applicable: {summary.reason}")
        return
    print(f"Eligible:                  {'yes' if summary.eligible else 'no'}")
    print(f"{summary.top_grade_label} population:         {summary.top_grade_pop if summary.top_grade_pop is not None else '(none)'}")
    print(f"Market supported:          {'yes' if summary.market_supported else 'no'}")
    print(f"Scarcity tier:             {summary.scarcity_tier}")
    print(f"Premium pct:               {summary.premium_pct:.0%}")
    print(f"Adjusted high-side value:  {summary.adjusted_high_value if summary.adjusted_high_value is not None else '(none)'}")
    print(f"Seller max value:          {summary.seller_max_value if summary.seller_max_value is not None else '(none)'}")
    print(f"Reason:                    {summary.reason}")


def choose_model_from_selection(selection_name: str):
    if selection_name == MODEL_B_NAME:
        return MODEL_B
    return MODEL_A


def resolve_filter_inputs(
    inherited_filters: Optional[dict[str, Any]] = None,
) -> tuple[str, str, str, Optional[float], Optional[bool], str, Optional[int]]:
    inherited_filters = inherited_filters or {}

    inherited_player_name = _norm(str(inherited_filters.get("player_name", "")))
    inherited_card_number = _norm(str(inherited_filters.get("card_number", "")))
    inherited_grader = normalize_grader(inherited_filters.get("grader"))
    inherited_grade_value = coerce_inherited_grade_value(inherited_filters.get("grade_value"))
    inherited_require_graded = inherited_filters.get("require_graded", None)

    launched_from_scraper = any(
        [
            inherited_player_name,
            inherited_card_number,
            inherited_grader,
            inherited_grade_value is not None,
            inherited_require_graded is not None,
        ]
    )

    if launched_from_scraper:
        player_name = inherited_player_name
        card_number = inherited_card_number
        grader = inherited_grader
        grade_value = inherited_grade_value
        require_graded = inherited_require_graded
    else:
        player_name = prompt_player_name_optional()
        card_number = prompt_card_number_optional()
        grader = prompt_grade_company_optional()
        grade_value = prompt_grade_value_optional()
        require_graded = prompt_require_graded_optional()

    manual_override = prompt_manual_model_override_optional()

    top_grade_pop: Optional[int] = None
    top_grade_label = _get_top_grade_label(grader, grade_value)
    if top_grade_label:
        top_grade_pop = prompt_top_grade_population_optional(top_grade_label)

    return (
        player_name,
        card_number,
        grader,
        grade_value,
        require_graded,
        manual_override,
        top_grade_pop,
    )



def _run_lane_valuation(
    *,
    sport: str,
    year_filter: str,
    player_name: str,
    card_number: str,
    manual_override: str,
    top_grade_pop: Optional[int],
    lane_label: str,
    lane_rows: list[dict[str, Any]],
    lane_grader: str,
    lane_grade_value: Optional[float],
    lane_require_graded: Optional[bool],
) -> tuple[list[dict[str, Any]], LaneResult]:
    print_filtered_rows_report(lane_rows)
    buckets = build_comp_buckets(lane_rows)
    bucket_info = bucket_summary(buckets)
    # print rounded bucket values
    bucket_info["recent_median_value"] = _fmt_money(buckets.recent_median_value) if buckets.recent_median_value is not None else "(none)"
    bucket_info["strong_bin_value"] = _fmt_money(buckets.strong_bin_value) if buckets.strong_bin_value is not None else "(none)"
    bucket_info["peak_auction_value"] = _fmt_money(buckets.peak_auction_value) if buckets.peak_auction_value is not None else "(none)"
    print_bucket_report(bucket_info)

    selector_input = LiquiditySelectorInput(
        sport=sport,
        year=int(year_filter) if year_filter.isdigit() else 0,
        set_name="",
        player_name=player_name or None,
        card_number=card_number or None,
        filtered_comp_count=len(lane_rows),
        recent_median_value=buckets.recent_median_value,
        strong_bin_value=buckets.strong_bin_value,
        peak_auction_value=buckets.peak_auction_value,
        manual_model_override=manual_override or None,
    )
    selection = select_liquidity_model(selector_input)
    print_selector_report(selection)

    selected_model = choose_model_from_selection(selection.selected_model_name)
    valuation = apply_liquidity_model(buckets, selected_model, rebalance_missing=False)

    scarcity_summary = build_scarcity_adjustment(
        grader=lane_grader,
        grade_value=lane_grade_value,
        top_grade_pop=top_grade_pop,
        selection_model_name=selection.selected_model_name,
        filtered_rows=lane_rows,
        strong_bin_count=int(bucket_info.get("strong_bin_count") or 0),
        blended_value=valuation.blended_value,
    )

    display_result = valuation
    print_valuation_report(display_result)
    print_scarcity_report(scarcity_summary)

    low_value = buckets.recent_median_value
    mid_value = valuation.blended_value
    high_value = scarcity_summary.adjusted_high_value if scarcity_summary.adjusted_high_value is not None else valuation.blended_value
    valuation_range = _format_range(low_value, mid_value, high_value)
    valuation_note = _build_valuation_note(
        lane_label=lane_label,
        model_label=selection.selected_model_name,
        comp_count=len(lane_rows),
        grader_note=_infer_grader_note(lane_grader, lane_grade_value, lane_require_graded),
        scarcity_pct=scarcity_summary.premium_pct,
    )

    outlier_high_rows, outlier_low_rows = _find_outlier_row_ids(lane_rows, buckets.recent_median_value)

    lane_result = LaneResult(
        lane_label=lane_label,
        grader=lane_grader,
        grade_value=lane_grade_value,
        rows=lane_rows,
        valuation_range=valuation_range,
        valuation_note=valuation_note,
        recent_median_value=buckets.recent_median_value,
        blended_value=valuation.blended_value,
        seller_max_value=scarcity_summary.seller_max_value,
        selected_model_name=selection.selected_model_name,
        scarcity_summary=scarcity_summary,
        outlier_high_rows=outlier_high_rows,
        outlier_low_rows=outlier_low_rows,
    )

    print_filtered_rows_report(lane_rows, lane_label=lane_label, valuation_range=valuation_range, valuation_note=valuation_note)
    return lane_rows, lane_result


def run_valuation_flow(
    *,
    normalized_csv_path: Path,
    sport: str,
    year_filter: str = "",
    inherited_filters: Optional[dict[str, Any]] = None,
) -> None:
    (
        player_name,
        card_number,
        grader,
        grade_value,
        require_graded,
        manual_override,
        top_grade_pop,
    ) = resolve_filter_inputs(inherited_filters)

    print_selected_file_context(
        sport=sport,
        year_filter=year_filter,
        csv_path=normalized_csv_path,
    )

    print_filter_context(
        player_name=player_name,
        card_number=card_number,
        grader=grader,
        grade_value=grade_value,
        require_graded=require_graded,
    )

    normalized_rows = load_csv_rows(normalized_csv_path)
    for idx, row in enumerate(normalized_rows):
        row["_row_id"] = f"comp-{idx+1}"
    print(f"\nLoaded normalized rows: {len(normalized_rows)}")

    criteria = CompFilterCriteria(
        sport=sport,
        year=int(year_filter) if year_filter.isdigit() else 0,
        set_name="",
        player_name=player_name or None,
        card_number=card_number or None,
        grader=grader or None,
        grade_value=grade_value,
        require_graded=require_graded,
    )

    filtered_rows = filter_comps(normalized_rows, criteria)
    print(f"Filtered rows:          {len(filtered_rows)}")

    if not filtered_rows:
        print("\nNo filtered comps matched the current criteria.")
        print("Try broadening the inputs:")
        print(" - remove grader/grade filters")
        print(" - clear card #")
        print(" - shorten player name")
        print(" - choose a broader normalized CSV")
        return

    groups = _group_rows_for_valuation(
        filtered_rows,
        grader=grader,
        grade_value=grade_value,
        require_graded=require_graded,
    )

    lane_results: list[LaneResult] = []
    valuation_export_rows: list[dict[str, Any]] = []

    for index, group in enumerate(groups):
        if len(groups) > 1:
            print_section(f"Valuation Lane {index + 1}: {group['lane_label']}")
        _, lane_result = _run_lane_valuation(
            sport=sport,
            year_filter=year_filter,
            player_name=player_name,
            card_number=card_number,
            manual_override=manual_override,
            top_grade_pop=top_grade_pop,
            lane_label=group["lane_label"],
            lane_rows=group["rows"],
            lane_grader=group["lane_grader"],
            lane_grade_value=group["lane_grade_value"],
            lane_require_graded=group["lane_require_graded"],
        )
        lane_results.append(lane_result)
        valuation_export_rows.extend(
            _build_filtered_row_display(
                group["rows"],
                lane_result.lane_label,
                lane_result.valuation_range,
                lane_result.valuation_note,
            )
        )

    valuation_csv_path = normalized_csv_path.with_name(normalized_csv_path.name.replace("_normalized.csv", "_valuation.csv"))
    valuation_json_path = normalized_csv_path.with_name(normalized_csv_path.name.replace("_normalized.csv", "_valuation.json"))
    valuation_html_path = normalized_csv_path.with_name(normalized_csv_path.name.replace("_normalized.csv", "_valuation_report.html"))

    with valuation_csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FILTERED_ROW_COLUMNS)
        writer.writeheader()
        writer.writerows(valuation_export_rows)
    print(f"Valuation CSV written: {valuation_csv_path}")

    payload = {
        "card_title": (str((inherited_filters or {}).get("search_keywords") or (inherited_filters or {}).get("search_string") or " ".join(part for part in [year_filter, player_name, card_number] if part).strip() or normalized_csv_path.stem)).upper(),
        "source_csv": str(normalized_csv_path),
        "lanes": [
            {
                "lane_label": lane.lane_label,
                "grader": lane.grader,
                "grade_value": lane.grade_value,
                "valuation_range": lane.valuation_range,
                "valuation_note": lane.valuation_note,
                "seller_max_value": lane.seller_max_value,
                "outlier_high_rows": lane.outlier_high_rows,
                "outlier_low_rows": lane.outlier_low_rows,
                "comp_count": len(lane.rows),
            }
            for lane in lane_results
        ],
    }
    valuation_json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Valuation JSON written: {valuation_json_path}")

    search_title = ""
    if inherited_filters:
        search_title = str(inherited_filters.get("search_keywords") or inherited_filters.get("search_string") or "").strip()
    if not search_title:
        search_title = " ".join(part for part in [year_filter, player_name, card_number] if part).strip() or normalized_csv_path.stem
    card_title = search_title.upper()
    primary_model = lane_results[0].selected_model_name if lane_results else ""
    subtitle = f"{sport} Valuation Report"
    if primary_model:
        subtitle = f'{subtitle}: <span class="subtitle-model">{html_lib.escape(primary_model)}</span>'

    html = _build_html_report(
        card_title=card_title,
        subtitle=subtitle,
        source_csv=normalized_csv_path,
        lane_results=lane_results,
    )
    valuation_html_path.write_text(html, encoding="utf-8")
    print(f"HTML report written: {valuation_html_path}")
    _open_html_report(valuation_html_path)


def main() -> None:
    sport = prompt_sport_scrollable()
    year_filter = prompt_year_filter_optional()

    files = list_normalized_comp_files(sport)
    files = filter_comp_files_by_year(files, year_filter)

    if not files:
        print(f"\nNo normalized CSV files found for sport={sport!r} year_filter={year_filter!r}.")
        print("Run the sold comps scraper first, or widen the year filter.")
        sys.exit(1)

    normalized_csv_path = prompt_normalized_csv_file(files)

    run_valuation_flow(
        normalized_csv_path=normalized_csv_path,
        sport=sport,
        year_filter=year_filter,
        inherited_filters=None,
    )


if __name__ == "__main__":
    main()
